---
title: "YFRW Modelling"
output: html_notebook
---

```{r setup}
library(pacman)
p_load(tidyverse, mgcv, mgcViz, car, RColorBrewer, wesanderson, sf, terra, mapview)

# function to calculate deviance explained from model
dx <- function(m) {
  return(round((m$null.deviance - m$deviance) / m$null.deviance * 100, 1))
}

data_path_lauren <- "../New GAM/"

all <- readxl::read_excel(paste0(data_path_lauren, "all.xlsx"))
nice_names <- readxl::read_excel(paste0(data_path_lauren, "nicenames.xlsx"))

all$Region <- as.factor(all$Region)
all$groupID <- as.factor(all$groupID)


```

# Statistical modelling
```{r single variables - Table 2}
#  [1] "pointid"     "count"       "X"           "Y"           "solar_sum"  
#  [6] "solar_wint"  "ruggedness"  "jaxa_dem"    "dem"         "slope"      
# [11] "aspect"      "T"           "rain"        "YFRW_SDM"    "Presence"   
# [16] "count1"      "count5"      "Region"      "Temperature" "Rainfall"   
# [21] "groupID"  

mT <- gam(log(count1) ~ s(Temperature), data = all,  method = "REML", family = tw())
plot(mT)
gam.check(mT)
summary(mT)

mdem <- gam(log(count1) ~ s(dem), data = all,  method = "REML", family = tw())
plot(mdem)
gam.check(mdem)
summary(mdem)

mjaxadem <- gam(log(count1) ~ s(jaxa_dem), data = all,  method = "REML", family = tw())
plot(mjaxadem)
gam.check(mjaxadem)
summary(mjaxadem)

mrug <- gam(log(count1) ~ s(ruggedness), data = all,  method = "REML", family = tw())
plot(mrug)
gam.check(mrug)
summary(mrug)

mslope <- gam(log(count1) ~ s(slope), data = all,  method = "REML", family = tw())
plot(mslope)
gam.check(mslope)
summary(mslope)

maspect <- gam(log(count1) ~ s(aspect), data = all,  method = "REML", family = tw())
plot(maspect)
gam.check(maspect)
summary(maspect)

msolwin <- gam(log(count1) ~ s(solar_wint), data = all,  method = "REML", family = tw())
plot(msolwin)
gam.check(msolwin)
summary(msolwin)

msolsum <- gam(log(count1) ~ s(solar_sum), data = all,  method = "REML", family = tw())
plot(msolsum)
gam.check(msolsum)
summary(msolsum)

mTR <- gam(log(count1) ~ s(Temperature, by = Region), data = all,  method = "REML", family = tw())
plot(mTR)
gam.check(mTR)
summary(mTR)

mdemR <- gam(log(count1) ~ s(dem, by = Region), data = all,  method = "REML", family = tw())
plot(mdemR)
gam.check(mdemR)
summary(mdemR)

mjaxademR <- gam(log(count1) ~ s(jaxa_dem, by = Region), data = all,  method = "REML", family = tw())
plot(mjaxademR)
gam.check(mjaxademR)
summary(mjaxademR)

mrugR <- gam(log(count1) ~ s(ruggedness, by = Region), data = all,  method = "REML", family = tw())
plot(mrugR)
gam.check(mrugR)
summary(mrugR)

mslopeR <- gam(log(count1) ~ s(slope, by = Region), data = all,  method = "REML", family = tw())
plot(mslopeR)
gam.check(mslopeR)
summary(mslopeR)

maspectR <- gam(log(count1) ~ s(aspect, by = Region), data = all,  method = "REML", family = tw())
plot(maspectR)
gam.check(maspectR)
summary(maspectR)

msolwinR <- gam(log(count1) ~ s(solar_wint, by = Region), data = all,  method = "REML", family = tw())
plot(msolwinR)
gam.check(msolwinR)
summary(msolwinR)

msolsumR <- gam(log(count1) ~ s(solar_sum, by = Region), data = all,  method = "REML", family = tw())
plot(msolsumR)
gam.check(msolsumR)
summary(msolsumR)

AT <- anova.gam(mT, mTR, test = "F")$`Pr(>Chi)`[2]
adem <- anova.gam(mdem, mdemR, test = "F")$`Pr(>Chi)`[2]
ajaxadem <- anova.gam(mjaxadem, mjaxademR, test = "F")$`Pr(>Chi)`[2]
arug <- anova.gam(mrug, mrugR, test = "F")$`Pr(>Chi)`[2]
aslope <- anova.gam(mslope, mslopeR, test = "F")$`Pr(>Chi)`[2]
aaspect <- anova.gam(maspect, maspectR, test = "F")$`Pr(>Chi)`[2]
asolwin <- anova.gam(msolwin, msolwinR, test = "F")$`Pr(>Chi)`[2]
asolsum <- anova.gam(msolsum, msolsumR, test = "F")$`Pr(>Chi)`[2]

anovaSig <- c(AT, adem, ajaxadem, arug, aslope, aaspect, asolwin, asolsum)

dev_ex_single <- c(dx(mT), dx(mdem), dx(mjaxadem), dx(mrug), dx(mslope), dx(maspect), dx(msolwin), dx(msolsum))

dev_ex_singleR <- c(dx(mTR), dx(mdemR), dx(mjaxademR), dx(mrugR), dx(mslopeR), dx(maspectR), dx(msolwinR), dx(msolsumR))

Table2 <- tibble(variable = nice_names$txt[c(19, 9, 8, 7, 10, 11, 6, 5)], 
                 'Deviance explained' = dev_ex_single, 
                 'Deviance explained by region' = dev_ex_singleR,
                 'Significance, regional difference' = anovaSig)

writexl::write_xlsx(Table2, "table2.xlsx")
```


```{r adding variables - Table 3}
# F2 <- gam(log(count1) ~ s(Temperature) + s(ruggedness), data = all,  method = "REML", family = tw())
# print(mgcViz::plot.gamViz((F2)), page = 1)
# gam.check(F2)
# summary((F2))
# 
# F2R <- gam(log(count1) ~ s(Temperature, by = Region) +  s(ruggedness, by=Region),
#            data = all,  method = "REML", family = tw())
# #print(plot((F2R)), pages = 1)
# print(mgcViz::plot.gamViz(F2R), page = 1)
# gam.check(F2R)
# summary((F2R))

F2i <- gam(log(count1) ~ te(Temperature, ruggedness), data = all,  method = "REML", family = tw())
mgcViz::plot.gamViz((F2i)) %>% print(page = 1)
gam.check(F2i)
summary((F2i))

F2iR <- gam(log(count1) ~ 
             te(Temperature, ruggedness, by = Region), data = all,  method = "REML", 
            family = tw())
#print(plot((F2iR)), pages = 1)
mgcViz::plot.gamViz(F2iR) %>% print(page = 1)

gam.check(F2iR)
summary.gam((F2iR))


F2slope <- gam(log(count1) ~ te(Temperature, ruggedness) + 
                 s(slope)  , data = all,  method = "REML", family = tw())

F2aspect <- gam(log(count1) ~  te(Temperature, ruggedness) + 
                 s(aspect),
                data = all,  method = "REML", family = tw())

F2solsum <- gam(log(count1) ~  te(Temperature, ruggedness) + 
                 s(solar_sum), 
                data = all,  method = "REML", family = tw())

F2solwin <- gam(log(count1) ~  te(Temperature, ruggedness) +  
                 s(solar_wint), 
                data = all,  method = "REML", family = tw())

            
F2slopeR <- gam(log(count1) ~  te(Temperature, ruggedness, by=Region) + 
                 s(slope, by=Region)  , data = all,  method = "REML", family = tw())

F2aspectR <- gam(log(count1) ~ te(Temperature, ruggedness, by=Region) + 
                 s(aspect, by=Region)  , data = all,  method = "REML", family = tw())

F2solsumR <- gam(log(count1) ~ te(Temperature, ruggedness, by=Region) + 
                 s(solar_sum, by=Region)  , data = all,  method = "REML", family = tw())

F2solwinR <- gam(log(count1) ~ te(Temperature, ruggedness, by=Region) + 
                 s(solar_wint, by=Region)  , data = all,  method = "REML", family = tw())

base_models <- c(dx(F2), dx(F2R), dx(F2i), dx(F2iR))


dev_ex_2 <- c(dx(F2i), dx(F2slope), dx(F2aspect), dx(F2solwin), dx(F2solsum))
dev_ex_2R <- c(dx(F2iR), dx(F2slopeR), dx(F2aspectR), dx(F2solwinR), dx(F2solsumR))
              

a2R <- anova.gam(F2i, F2iR, test = "F")
#a2i <- anova.gam(F2, F2i, test = "F")

a2slope <- anova.gam(F2i, F2slope, test = "F")
a2aspect <- anova.gam(F2i, F2aspect, test = "F")
a2solsum <- anova.gam(F2i, F2solsum, test = "F")
a2solwin <- anova.gam(F2i, F2solwin, test = "F")

a2slopeR <- anova.gam(F2slope, F2slopeR, test = "F")
a2aspectR <- anova.gam(F2aspect, F2aspectR, test = "F")
a2solsumR <- anova.gam(F2solsum, F2solsumR, test = "F")
a2solwinR <- anova.gam(F2solwin, F2solwinR, test = "F")

p_ <- function(mod) {return(mod$`Pr(>Chi)`[2])}

anova_sig2 <- c(NA, p_(a2slope), p_(a2aspect), p_(a2solsum), p_(a2solwin))
regdiff_sig2R <- c(p_(a2R), p_(a2slopeR), p_(a2aspectR), p_(a2solsumR), p_(a2solwinR))

Table3 <- tibble(variable = c("Base model", nice_names$txt[c(10, 11, 6, 5)]),
                 'Deviance explained' = dev_ex_2,
                 'Deviance explained +region' = dev_ex_2R,
                 'Significance, regional difference' = regdiff_sig2R,
                 'ANOVA p-value' = anova_sig2)


writexl::write_xlsx(Table3, "table3.xlsx")

```


## For Supplementary Material Fig S2
```{r setup}
library(pacman)
p_load(tidyverse, mgcv, mgcViz, car, RColorBrewer, wesanderson, sf, terra, mapview)

# function to calculate deviance explained from model
dx <- function(m) {
  return(round((m$null.deviance - m$deviance) / m$null.deviance * 100, 1))
}

data_path_lauren <- "../New GAM/"

all <- readxl::read_excel(paste0(data_path_lauren, "all.xlsx"))
nice_names <- readxl::read_excel(paste0(data_path_lauren, "nicenames.xlsx"))
all$Region <- as.factor(all$Region)
all$groupID <- as.factor(all$groupID)

```

```{r colours}
# choose distinct colours -  wesanderson palettes
#  https://github.com/karthik/wesanderson
names(wes_palettes)
mycols_wes <- c(wes_palette("Darjeeling2"), wes_palette("Darjeeling1"),
                wes_palette("Chevalier1"), wes_palette("BottleRocket2"), 
                wes_palette("Moonrise1"), wes_palette("Moonrise2"), 
                wes_palette("Moonrise3"), wes_palette("GrandBudapest1"), 
                wes_palette("GrandBudapest2"), wes_palette("IsleofDogs1") 
                )
mycols_wes <- mycols_wes[-5]
scales::show_col(mycols_wes)
scales::show_col(mycols_wes[1:5])


# create nice colours for Flinders and Olary
ngroups <- length(unique(all$groupID))
if(ngroups == 5) {
  site_colours <- mycols_wes[c(2,12,5,6,14)]
} else {
  # automatic for variable numbers
  fg_sites <- all %>% 
    filter(Region == "Flinders_Gammon_Ranges") %>% 
    select(groupID) %>% pull() %>%
    unique() 
  ol_sites <- points %>% 
    filter(Region == "Olary_Ranges") %>% 
    select(groupID) %>% pull %>%
    unique()
  flinders_cols <- mycols_wes[c(3:(2 + length(fg_sites)))]
  olary_cols <- mycols_wes[c(12:(11 + length(ol_sites)))]
  # create colours for sites
  site_colours <- c(flinders_cols, olary_cols)
}
```

```{r correlation matrix by Region and GroupID}
# remove sites with low number of members and take sample for better visualisation

all_select <- all %>%
  # filter(groupID %in% which(sites$n > 200)) %>%
  sample_n(1000) %>%
  droplevels

suppressWarnings(scatterplotMatrix(~log(count1)+Temperature+Rainfall+dem+ruggedness+aspect+slope+solar_sum+solar_wint|Region, 
                  data=all_select,
                  col=c('#E69F00', 'darkblue'),
                  regLine=F,
                  # smooth = list(method=gamLine, k=30),
                  cex=0.2,
                  main="Scatter plot for Flinders_Gammon_Ranges (sand) Olary_Ranges (blue)"
  )
)

```

